spring.application.name=Order-Service
server.port=8080
# DB Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Resilience4j configurations:
#setting the Failure Rate to 50%
resilience4j.circuitbreaker.instances.projectService.failure-rate-threshold=50
#It will check After minimum 5 failed calls
resilience4j.circuitbreaker.instances.projectService.minimum-number-of-calls=5
#Sample size of 10 to calculate Failure
resilience4j.circuitbreaker.instances.projectService.sliding-window-size=10
# time to wait before trying again
resilience4j.circuitbreaker.instances.projectService.wait-duration-in-open-state=10s